# The Complete Guide to Polars for Data Science

[![Open in Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/norochalise/noroinsight-polars-tutorial/blob/main/Complete_Guide_to_Polars.ipynb)

This is part of the original article [The Complete Guide to Polars for Data Science](https://noroinsight.com/polars-for-data-science-complete-guide/)

## Dataset & Code Repository

This guide uses the Customer Transactions & Spending Dataset (1M Rows), which includes customer demographics, spending behavior, and payment details:

- [Kaggle Dataset: Customer Transactions & Spending (1M Rows)](https://www.kaggle.com/datasets/mountboy/online-store-customer-transactions-1m-rows)
- [Read the full article on Noro Insight](https://noroinsight.com/polars-for-data-science-complete-guide/)

Every cell is tested on **Polars 2.0** with the current version of the dataset. The notebook downloads the data for you.

## 1. Setup

In [1]:
# Install Polars and kagglehub (to download the dataset)
!pip install -q "polars>=2.0" kagglehub

In [2]:
# Import libraries
import os
import polars as pl
import kagglehub

print("Polars", pl.__version__)  # This notebook is tested on Polars 2.0

Polars 2.0.0

**Download the dataset**

This downloads the dataset from Kaggle (no login needed). If you already have the CSV, set `DATA_PATH` to its location instead.

In [3]:
DATA_PATH = os.path.join(
    kagglehub.dataset_download("mountboy/online-store-customer-transactions-1m-rows"),
    "customer_spending_1M_2018_2025.csv",
)
DATA_PATH

In [4]:
# Setting Display Options
import polars as pl

pl.Config.set_tbl_rows(10)  # Show 10 rows
pl.Config.set_tbl_cols(15)   # Show 15 columns
pl.Config.set_fmt_str_lengths(90)  # Increase max string column width

polars.config.Config

## 2. Loading and Saving Data

**Reading CSV Files**

In [5]:
# Reading CSV Files
df = pl.read_csv(DATA_PATH)
df.head()

shape: (5, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 1000    ┆ 2018-01 ┆ Female ┆ 39  ┆ Single  ┆ Oklaho ┆ Platin ┆ Unempl ┆ Card   ┆ 0      ┆ 1557.5 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ ma     ┆ um     ┆ oyment ┆        ┆        ┆        │
│         ┆ 04:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1001    ┆ 2018-01 ┆ Male   ┆ 34  ┆ Married ┆ Hawaii ┆ Basic  ┆ worker ┆ PayPal ┆ 1      ┆ 153.55 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ s      ┆        ┆        ┆        │
│         ┆ 06:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1002    ┆ 2018-01 ┆ Female ┆ 53  ┆ Married ┆ Iowa   ┆ Basic  ┆ self-e ┆ PayPal ┆ 1      ┆ 2640.9 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ mploye ┆        ┆        ┆ 6      │
│         ┆ 14:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1003    ┆ 2018-01 ┆ Male   ┆ 33  ┆ Married ┆ Wiscon ┆ Basic  ┆ self-e ┆ Card   ┆ 1      ┆ 293.58 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ sin    ┆        ┆ mploye ┆        ┆        ┆        │
│         ┆ 23:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1004    ┆ 2018-01 ┆ Female ┆ 36  ┆ Married ┆ Texas  ┆ Platin ┆ Employ ┆ Card   ┆ 0      ┆ 1608.0 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆ um     ┆ ees    ┆        ┆        ┆ 1      │
│         ┆ 25:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

**Reading Other File Formats**

In [6]:
# Create small example files in other formats so this cell runs on its own
df.head(1000).write_parquet("online_store_data.parquet")
df.head(1000).write_json("customer_data.json")
df.head(1000).write_ipc("online_store_data.feather")

# Read a Parquet file (Recommended for large datasets)
df_parquet = pl.read_parquet("online_store_data.parquet")

# Read a JSON file
df_json = pl.read_json("customer_data.json")

# Read an IPC/Feather file (Optimized for fast in-memory processing)
df_ipc = pl.read_ipc("online_store_data.feather")

# Read an Avro file (Commonly used for efficient data pipelines)
# df_avro = pl.read_avro("online_store_data.avro")

**Reading CSV with Additional Parameters**

In [7]:
df_skipped = pl.read_csv(
    DATA_PATH,
    skip_rows=2  # Skip first two rows if they contain metadata
)

**Handling Files Without a Header Row**

By default the first row becomes the column names. For a file with no header row, say so and supply the names yourself:

In [8]:
# Create a small example file with no header row (4 columns)
df.head(5).select("Transaction_ID", "Transaction_date", "Gender", "Age").write_csv("customer_data_no_header.csv", include_header=False)

df_no_header = pl.read_csv(
    "customer_data_no_header.csv",
    has_header=False,  # The first row is data, not column names
    new_columns=["Transaction_ID", "Transaction_date", "Gender", "Age"],
)
df_no_header

shape: (5, 4)
┌────────────────┬────────────────────────────┬────────┬─────┐
│ Transaction_ID ┆ Transaction_date           ┆ Gender ┆ Age │
│ ---            ┆ ---                        ┆ ---    ┆ --- │
│ i64            ┆ str                        ┆ str    ┆ i64 │
╞════════════════╪════════════════════════════╪════════╪═════╡
│ 1000           ┆ 2018-01-01T00:04:00.000000 ┆ Female ┆ 39  │
│ 1001           ┆ 2018-01-01T00:06:00.000000 ┆ Male   ┆ 34  │
│ 1002           ┆ 2018-01-01T00:14:00.000000 ┆ Female ┆ 53  │
│ 1003           ┆ 2018-01-01T00:23:00.000000 ┆ Male   ┆ 33  │
│ 1004           ┆ 2018-01-01T00:25:00.000000 ┆ Female ┆ 36  │
└────────────────┴────────────────────────────┴────────┴─────┘

**Reading CSV from a URL**

In [9]:
df_url = pl.read_csv("https://raw.githubusercontent.com/norochalise/pandas-tutorial-article-2022/refs/heads/main/dataset/online_store_customer_data.csv")

**Streaming Large Datasets with scan_csv()**

In [10]:
df_stream = pl.scan_csv(DATA_PATH)

# Apply filtering before loading into memory
df_filtered = df_stream.filter(pl.col("Amount_spent") > 50)

# Collect to load the required data into memory
df_final = df_filtered.collect()
df_final.head(3)

shape: (3, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 1000    ┆ 2018-01 ┆ Female ┆ 39  ┆ Single  ┆ Oklaho ┆ Platin ┆ Unempl ┆ Card   ┆ 0      ┆ 1557.5 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ ma     ┆ um     ┆ oyment ┆        ┆        ┆        │
│         ┆ 04:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1001    ┆ 2018-01 ┆ Male   ┆ 34  ┆ Married ┆ Hawaii ┆ Basic  ┆ worker ┆ PayPal ┆ 1      ┆ 153.55 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ s      ┆        ┆        ┆        │
│         ┆ 06:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1002    ┆ 2018-01 ┆ Female ┆ 53  ┆ Married ┆ Iowa   ┆ Basic  ┆ self-e ┆ PayPal ┆ 1      ┆ 2640.9 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ mploye ┆        ┆        ┆ 6      │
│         ┆ 14:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

**Saving Data Files**

In [11]:
# Save DataFrame as CSV
df.write_csv("customer_data.csv")

# Save DataFrame as Parquet (recommended for large datasets)
df.write_parquet("customer_data.parquet")

# Save DataFrame as JSON
df.write_json("customer_data.json")

# Save DataFrame as IPC/Feather
df.write_ipc("customer_data.feather")

## 3. Data Exploration and Manipulation

### Viewing Data (Head, Tail, Schema, Describe)

**Checking the First Few Rows**

In [12]:
df.head()  # Shows the first 5 rows

shape: (5, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 1000    ┆ 2018-01 ┆ Female ┆ 39  ┆ Single  ┆ Oklaho ┆ Platin ┆ Unempl ┆ Card   ┆ 0      ┆ 1557.5 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ ma     ┆ um     ┆ oyment ┆        ┆        ┆        │
│         ┆ 04:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1001    ┆ 2018-01 ┆ Male   ┆ 34  ┆ Married ┆ Hawaii ┆ Basic  ┆ worker ┆ PayPal ┆ 1      ┆ 153.55 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ s      ┆        ┆        ┆        │
│         ┆ 06:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1002    ┆ 2018-01 ┆ Female ┆ 53  ┆ Married ┆ Iowa   ┆ Basic  ┆ self-e ┆ PayPal ┆ 1      ┆ 2640.9 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ mploye ┆        ┆        ┆ 6      │
│         ┆ 14:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1003    ┆ 2018-01 ┆ Male   ┆ 33  ┆ Married ┆ Wiscon ┆ Basic  ┆ self-e ┆ Card   ┆ 1      ┆ 293.58 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ sin    ┆        ┆ mploye ┆        ┆        ┆        │
│         ┆ 23:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1004    ┆ 2018-01 ┆ Female ┆ 36  ┆ Married ┆ Texas  ┆ Platin ┆ Employ ┆ Card   ┆ 0      ┆ 1608.0 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆ um     ┆ ees    ┆        ┆        ┆ 1      │
│         ┆ 25:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

**Viewing the Last Few Rows**

In [13]:
df.tail()  # Shows the last 5 rows

shape: (5, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 1000995 ┆ 2025-01 ┆ Male   ┆ 45  ┆ Single  ┆ Arkans ┆ Gold   ┆ Employ ┆ PayPal ┆ 1      ┆ 1762.7 │
│         ┆ -30T23: ┆        ┆     ┆         ┆ as     ┆        ┆ ees    ┆        ┆        ┆ 6      │
│         ┆ 43:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000996 ┆ 2025-01 ┆ Female ┆ 75  ┆ Married ┆ Virgin ┆ Silver ┆ worker ┆ Other  ┆ 1      ┆ 31.41  │
│         ┆ -30T23: ┆        ┆     ┆         ┆ ia     ┆        ┆ s      ┆        ┆        ┆        │
│         ┆ 45:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000997 ┆ 2025-01 ┆ Female ┆ 61  ┆ Married ┆ Kansas ┆ Basic  ┆ self-e ┆ Other  ┆ 1      ┆ 1699.3 │
│         ┆ -30T23: ┆        ┆     ┆         ┆        ┆        ┆ mploye ┆        ┆        ┆ 1      │
│         ┆ 47:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000998 ┆ 2025-01 ┆ Female ┆ 68  ┆ Married ┆ Utah   ┆ Basic  ┆ Employ ┆ PayPal ┆ 1      ┆ 208.26 │
│         ┆ -30T23: ┆        ┆     ┆         ┆        ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 52:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000999 ┆ 2025-01 ┆ Male   ┆ 55  ┆ Single  ┆ Nevada ┆ Missin ┆ worker ┆ PayPal ┆ 0      ┆ 2063.9 │
│         ┆ -30T23: ┆        ┆     ┆         ┆        ┆ g      ┆ s      ┆        ┆        ┆ 2      │
│         ┆ 57:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

**Retrieving Sample Rows from a DataFrame**

In [14]:
df.sample(n=4)

shape: (4, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 196474  ┆ 2019-05 ┆ Male   ┆ 34  ┆ Married ┆ South  ┆ Basic  ┆ null   ┆ PayPal ┆ 1      ┆ 786.73 │
│         ┆ -23T01: ┆        ┆     ┆         ┆ Dakota ┆        ┆        ┆        ┆        ┆        │
│         ┆ 08:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 712411  ┆ 2023-01 ┆ Male   ┆ 49  ┆ Married ┆ Delawa ┆ Platin ┆ Employ ┆ Other  ┆ 0      ┆ 2454.3 │
│         ┆ -16T10: ┆        ┆     ┆         ┆ re     ┆ um     ┆ ees    ┆        ┆        ┆ 7      │
│         ┆ 24:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 532148  ┆ 2021-10 ┆ Female ┆ 76  ┆ Single  ┆ Kansas ┆ Silver ┆ Employ ┆ PayPal ┆ 1      ┆ 82.27  │
│         ┆ -06T00: ┆        ┆     ┆         ┆        ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 14:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 153532  ┆ 2019-01 ┆ Male   ┆ 51  ┆ Married ┆ Alabam ┆ Platin ┆ self-e ┆ Other  ┆ 1      ┆ 1367.7 │
│         ┆ -31T19: ┆        ┆     ┆         ┆ a      ┆ um     ┆ mploye ┆        ┆        ┆ 7      │
│         ┆ 02:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

**Checking the Structure of the Data (df.schema)**

In [15]:
df.schema

Schema([('Transaction_ID', Int64),
        ('Transaction_date', String),
        ('Gender', String),
        ('Age', Int64),
        ('Marital_status', String),
        ('State_names', String),
        ('Segment', String),
        ('Employees_status', String),
        ('Payment_method', String),
        ('Referral', Int64),
        ('Amount_spent', Float64)])

**Summarizing Data**

In [16]:
df.describe()

shape: (9, 12)
┌────────┬────────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ statis ┆ Transa ┆ Transa ┆ Gende ┆ Age   ┆ Marit ┆ State ┆ Segme ┆ Emplo ┆ Payme ┆ Refer ┆ Amoun │
│ tic    ┆ ction_ ┆ ction_ ┆ r     ┆ ---   ┆ al_st ┆ _name ┆ nt    ┆ yees_ ┆ nt_me ┆ ral   ┆ t_spe │
│ ---    ┆ ID     ┆ date   ┆ ---   ┆ f64   ┆ atus  ┆ s     ┆ ---   ┆ statu ┆ thod  ┆ ---   ┆ nt    │
│ str    ┆ ---    ┆ ---    ┆ str   ┆       ┆ ---   ┆ ---   ┆ str   ┆ s     ┆ ---   ┆ f64   ┆ ---   │
│        ┆ f64    ┆ str    ┆       ┆       ┆ str   ┆ str   ┆       ┆ ---   ┆ str   ┆       ┆ f64   │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆ str   ┆       ┆       ┆       │
╞════════╪════════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ count  ┆ 1e6    ┆ 100000 ┆ 98894 ┆ 98334 ┆ 10000 ┆ 10000 ┆ 10000 ┆ 98977 ┆ 10000 ┆ 93818 ┆ 90393 │
│        ┆        ┆ 0      ┆ 8     ┆ 6.0   ┆ 00    ┆ 00    ┆ 00    ┆ 5     ┆ 00    ┆ 8.0   ┆ 5.0   │
│ null_c ┆ 0.0    ┆ 0      ┆ 11052 ┆ 16654 ┆ 0     ┆ 0     ┆ 0     ┆ 10225 ┆ 0     ┆ 61812 ┆ 96065 │
│ ount   ┆        ┆        ┆       ┆ .0    ┆       ┆       ┆       ┆       ┆       ┆ .0    ┆ .0    │
│ mean   ┆ 500999 ┆ null   ┆ null  ┆ 46.64 ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ 0.652 ┆ 1416. │
│        ┆ .5     ┆        ┆       ┆ 717   ┆       ┆       ┆       ┆       ┆       ┆ 339   ┆ 12610 │
│        ┆        ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 6     │
│ std    ┆ 288675 ┆ null   ┆ null  ┆ 18.18 ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ 0.476 ┆ 878.1 │
│        ┆ .27893 ┆        ┆       ┆ 3986  ┆       ┆       ┆       ┆       ┆       ┆ 228   ┆ 23082 │
│        ┆ 2      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ min    ┆ 1000.0 ┆ 2018-0 ┆ Femal ┆ 15.0  ┆ Marri ┆ Alaba ┆ Basic ┆ Emplo ┆ Card  ┆ 0.0   ┆ 2.09  │
│        ┆        ┆ 1-01T0 ┆ e     ┆       ┆ ed    ┆ ma    ┆       ┆ yees  ┆       ┆       ┆       │
│        ┆        ┆ 0:04:0 ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆        ┆ 0.0000 ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆        ┆ 00     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 25%    ┆ 251000 ┆ null   ┆ null  ┆ 32.0  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ 0.0   ┆ 677.3 │
│        ┆ .0     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 6     │
│ 50%    ┆ 501000 ┆ null   ┆ null  ┆ 47.0  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ 1.0   ┆ 1332. │
│        ┆ .0     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 48    │
│ 75%    ┆ 750999 ┆ null   ┆ null  ┆ 62.0  ┆ null  ┆ null  ┆ null  ┆ null  ┆ null  ┆ 1.0   ┆ 2037. │
│        ┆ .0     ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆ 59    │
│ max    ┆ 1.0009 ┆ 2025-0 ┆ Male  ┆ 78.0  ┆ Singl ┆ Wyomi ┆ Silve ┆ worke ┆ PayPa ┆ 1.0   ┆ 2999. │
│        ┆ 99e6   ┆ 1-30T2 ┆       ┆       ┆ e     ┆ ng    ┆ r     ┆ rs    ┆ l     ┆       ┆ 98    │
│        ┆        ┆ 3:57:0 ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆        ┆ 0.0000 ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│        ┆        ┆ 00     ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
└────────┴────────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┘

### Selecting, Filtering, and Slicing Data

**Selecting Specific Columns**

In [17]:
#Selecting One Column
df.select("Amount_spent")

shape: (1_000_000, 1)
┌──────────────┐
│ Amount_spent │
│ ---          │
│ f64          │
╞══════════════╡
│ 1557.5       │
│ 153.55       │
│ 2640.96      │
│ 293.58       │
│ 1608.01      │
│ …            │
│ 1762.76      │
│ 31.41        │
│ 1699.31      │
│ 208.26       │
│ 2063.92      │
└──────────────┘

In [18]:
# Selecting Multiple Columns
df.select(["Amount_spent", "Transaction_ID", "Gender"])

shape: (1_000_000, 3)
┌──────────────┬────────────────┬────────┐
│ Amount_spent ┆ Transaction_ID ┆ Gender │
│ ---          ┆ ---            ┆ ---    │
│ f64          ┆ i64            ┆ str    │
╞══════════════╪════════════════╪════════╡
│ 1557.5       ┆ 1000           ┆ Female │
│ 153.55       ┆ 1001           ┆ Male   │
│ 2640.96      ┆ 1002           ┆ Female │
│ 293.58       ┆ 1003           ┆ Male   │
│ 1608.01      ┆ 1004           ┆ Female │
│ …            ┆ …              ┆ …      │
│ 1762.76      ┆ 1000995        ┆ Male   │
│ 31.41        ┆ 1000996        ┆ Female │
│ 1699.31      ┆ 1000997        ┆ Female │
│ 208.26       ┆ 1000998        ┆ Female │
│ 2063.92      ┆ 1000999        ┆ Male   │
└──────────────┴────────────────┴────────┘

#### Filtering Rows Based on Conditions

In [19]:
# Filtering Rows Based on a Single Condition
df.filter(pl.col("Amount_spent") > 50)

shape: (889_589, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 1000    ┆ 2018-01 ┆ Female ┆ 39  ┆ Single  ┆ Oklaho ┆ Platin ┆ Unempl ┆ Card   ┆ 0      ┆ 1557.5 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ ma     ┆ um     ┆ oyment ┆        ┆        ┆        │
│         ┆ 04:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1001    ┆ 2018-01 ┆ Male   ┆ 34  ┆ Married ┆ Hawaii ┆ Basic  ┆ worker ┆ PayPal ┆ 1      ┆ 153.55 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ s      ┆        ┆        ┆        │
│         ┆ 06:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1002    ┆ 2018-01 ┆ Female ┆ 53  ┆ Married ┆ Iowa   ┆ Basic  ┆ self-e ┆ PayPal ┆ 1      ┆ 2640.9 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ mploye ┆        ┆        ┆ 6      │
│         ┆ 14:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1003    ┆ 2018-01 ┆ Male   ┆ 33  ┆ Married ┆ Wiscon ┆ Basic  ┆ self-e ┆ Card   ┆ 1      ┆ 293.58 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ sin    ┆        ┆ mploye ┆        ┆        ┆        │
│         ┆ 23:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1004    ┆ 2018-01 ┆ Female ┆ 36  ┆ Married ┆ Texas  ┆ Platin ┆ Employ ┆ Card   ┆ 0      ┆ 1608.0 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆ um     ┆ ees    ┆        ┆        ┆ 1      │
│         ┆ 25:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ …       ┆ …       ┆ …      ┆ …   ┆ …       ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 1000994 ┆ 2025-01 ┆ Female ┆ 51  ┆ Single  ┆ West   ┆ Platin ┆ Unempl ┆ Card   ┆ 0      ┆ 522.04 │
│         ┆ -30T23: ┆        ┆     ┆         ┆ Virgin ┆ um     ┆ oyment ┆        ┆        ┆        │
│         ┆ 29:00.0 ┆        ┆     ┆         ┆ ia     ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000995 ┆ 2025-01 ┆ Male   ┆ 45  ┆ Single  ┆ Arkans ┆ Gold   ┆ Employ ┆ PayPal ┆ 1      ┆ 1762.7 │
│         ┆ -30T23: ┆        ┆     ┆         ┆ as     ┆        ┆ ees    ┆        ┆        ┆ 6      │
│         ┆ 43:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000997 ┆ 2025-01 ┆ Female ┆ 61  ┆ Married ┆ Kansas ┆ Basic  ┆ self-e ┆ Other  ┆ 1      ┆ 1699.3 │
│         ┆ -30T23: ┆        ┆     ┆         ┆        ┆        ┆ mploye ┆        ┆        ┆ 1      │
│         ┆ 47:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000998 ┆ 2025-01 ┆ Female ┆ 68  ┆ Married ┆ Utah   ┆ Basic  ┆ Employ ┆ PayPal ┆ 1      ┆ 208.26 │
│         ┆ -30T23: ┆        ┆     ┆         ┆        ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 52:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000999 ┆ 2025-01 ┆ Male   ┆ 55  ┆ Single  ┆ Nevada ┆ Missin ┆ worker ┆ PayPal ┆ 0      ┆ 2063.9 │
│         ┆ -30T23: ┆        ┆     ┆         ┆        ┆ g      ┆ s      ┆        ┆        ┆ 2      │
│         ┆ 57:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

In [20]:
# Filtering Rows Based on Multiple Conditions
df.filter((pl.col("Amount_spent") > 100) & (pl.col("Gender") == "Female"))

shape: (466_044, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 1000    ┆ 2018-01 ┆ Female ┆ 39  ┆ Single  ┆ Oklaho ┆ Platin ┆ Unempl ┆ Card   ┆ 0      ┆ 1557.5 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ ma     ┆ um     ┆ oyment ┆        ┆        ┆        │
│         ┆ 04:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1002    ┆ 2018-01 ┆ Female ┆ 53  ┆ Married ┆ Iowa   ┆ Basic  ┆ self-e ┆ PayPal ┆ 1      ┆ 2640.9 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ mploye ┆        ┆        ┆ 6      │
│         ┆ 14:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1004    ┆ 2018-01 ┆ Female ┆ 36  ┆ Married ┆ Texas  ┆ Platin ┆ Employ ┆ Card   ┆ 0      ┆ 1608.0 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆ um     ┆ ees    ┆        ┆        ┆ 1      │
│         ┆ 25:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1006    ┆ 2018-01 ┆ Female ┆ 55  ┆ Single  ┆ Ohio   ┆ Silver ┆ Unempl ┆ PayPal ┆ 0      ┆ 1553.6 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ oyment ┆        ┆        ┆ 1      │
│         ┆ 29:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1007    ┆ 2018-01 ┆ Female ┆ 35  ┆ Married ┆ Hawaii ┆ Basic  ┆ worker ┆ Other  ┆ 1      ┆ 1851.5 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ s      ┆        ┆        ┆ 8      │
│         ┆ 29:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ …       ┆ …       ┆ …      ┆ …   ┆ …       ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 1000992 ┆ 2025-01 ┆ Female ┆ 25  ┆ Married ┆ Nebras ┆ Basic  ┆ worker ┆ PayPal ┆ 0      ┆ 1735.0 │
│         ┆ -30T23: ┆        ┆     ┆         ┆ ka     ┆        ┆ s      ┆        ┆        ┆ 7      │
│         ┆ 23:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000993 ┆ 2025-01 ┆ Female ┆ 18  ┆ Married ┆ Alabam ┆ Silver ┆ worker ┆ PayPal ┆ null   ┆ 2091.7 │
│         ┆ -30T23: ┆        ┆     ┆         ┆ a      ┆        ┆ s      ┆        ┆        ┆ 3      │
│         ┆ 29:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000994 ┆ 2025-01 ┆ Female ┆ 51  ┆ Single  ┆ West   ┆ Platin ┆ Unempl ┆ Card   ┆ 0      ┆ 522.04 │
│         ┆ -30T23: ┆        ┆     ┆         ┆ Virgin ┆ um     ┆ oyment ┆        ┆        ┆        │
│         ┆ 29:00.0 ┆        ┆     ┆         ┆ ia     ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000997 ┆ 2025-01 ┆ Female ┆ 61  ┆ Married ┆ Kansas ┆ Basic  ┆ self-e ┆ Other  ┆ 1      ┆ 1699.3 │
│         ┆ -30T23: ┆        ┆     ┆         ┆        ┆        ┆ mploye ┆        ┆        ┆ 1      │
│         ┆ 47:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000998 ┆ 2025-01 ┆ Female ┆ 68  ┆ Married ┆ Utah   ┆ Basic  ┆ Employ ┆ PayPal ┆ 1      ┆ 208.26 │
│         ┆ -30T23: ┆        ┆     ┆         ┆        ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 52:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

In [21]:
df.filter((pl.col("Marital_status") == "Married") & (pl.col("State_names") == "California"))

shape: (13_747, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 1085    ┆ 2018-01 ┆ Male   ┆ 33  ┆ Married ┆ Califo ┆ Basic  ┆ Employ ┆ Other  ┆ 0      ┆ 2621.9 │
│         ┆ -01T04: ┆        ┆     ┆         ┆ rnia   ┆        ┆ ees    ┆        ┆        ┆ 1      │
│         ┆ 59:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1107    ┆ 2018-01 ┆ Male   ┆ 65  ┆ Married ┆ Califo ┆ Basic  ┆ Unempl ┆ PayPal ┆ 1      ┆ 884.14 │
│         ┆ -01T06: ┆        ┆     ┆         ┆ rnia   ┆        ┆ oyment ┆        ┆        ┆        │
│         ┆ 11:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1140    ┆ 2018-01 ┆ Female ┆ 60  ┆ Married ┆ Califo ┆ Basic  ┆ Unempl ┆ Other  ┆ 0      ┆ 2785.7 │
│         ┆ -01T08: ┆        ┆     ┆         ┆ rnia   ┆        ┆ oyment ┆        ┆        ┆ 8      │
│         ┆ 41:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1335    ┆ 2018-01 ┆ Male   ┆ 61  ┆ Married ┆ Califo ┆ Basic  ┆ self-e ┆ PayPal ┆ 1      ┆ 670.59 │
│         ┆ -01T21: ┆        ┆     ┆         ┆ rnia   ┆        ┆ mploye ┆        ┆        ┆        │
│         ┆ 20:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1395    ┆ 2018-01 ┆ Female ┆ 28  ┆ Married ┆ Califo ┆ Gold   ┆ worker ┆ Card   ┆ 1      ┆ 1887.3 │
│         ┆ -02T01: ┆        ┆     ┆         ┆ rnia   ┆        ┆ s      ┆        ┆        ┆        │
│         ┆ 42:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ …       ┆ …       ┆ …      ┆ …   ┆ …       ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 1000583 ┆ 2025-01 ┆ Female ┆ 22  ┆ Married ┆ Califo ┆ Basic  ┆ worker ┆ PayPal ┆ 1      ┆ 1510.2 │
│         ┆ -30T00: ┆        ┆     ┆         ┆ rnia   ┆        ┆ s      ┆        ┆        ┆ 8      │
│         ┆ 04:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000586 ┆ 2025-01 ┆ Male   ┆ 49  ┆ Married ┆ Califo ┆ Basic  ┆ worker ┆ PayPal ┆ 1      ┆ 337.17 │
│         ┆ -30T00: ┆        ┆     ┆         ┆ rnia   ┆        ┆ s      ┆        ┆        ┆        │
│         ┆ 12:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000632 ┆ 2025-01 ┆ Female ┆ 28  ┆ Married ┆ Califo ┆ Basic  ┆ Employ ┆ PayPal ┆ 1      ┆ 1287.3 │
│         ┆ -30T02: ┆        ┆     ┆         ┆ rnia   ┆        ┆ ees    ┆        ┆        ┆ 1      │
│         ┆ 26:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000778 ┆ 2025-01 ┆ Male   ┆ 78  ┆ Married ┆ Califo ┆ Missin ┆ Employ ┆ Other  ┆ 1      ┆ 150.76 │
│         ┆ -30T10: ┆        ┆     ┆         ┆ rnia   ┆ g      ┆ ees    ┆        ┆        ┆        │
│         ┆ 31:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000972 ┆ 2025-01 ┆ Female ┆ 59  ┆ Married ┆ Califo ┆ Missin ┆ worker ┆ Card   ┆ 0      ┆ 880.28 │
│         ┆ -30T21: ┆        ┆     ┆         ┆ rnia   ┆ g      ┆ s      ┆        ┆        ┆        │
│         ┆ 55:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

### Extracting a Specific Range of Rows (Slicing)

**Extract a Range of Rows by Index**

In [22]:
df.slice(10, 10)  # Start at index 10, retrieve 10 rows (rows 10 to 19)

shape: (10, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 1010    ┆ 2018-01 ┆ Female ┆ 40  ┆ Single  ┆ Illino ┆ Basic  ┆ Unempl ┆ PayPal ┆ 1      ┆ 1160.6 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ is     ┆        ┆ oyment ┆        ┆        ┆ 5      │
│         ┆ 34:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1011    ┆ 2018-01 ┆ Male   ┆ 73  ┆ Married ┆ West   ┆ Basic  ┆ Employ ┆ PayPal ┆ 0      ┆ 1397.0 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ Virgin ┆        ┆ ees    ┆        ┆        ┆ 9      │
│         ┆ 36:00.0 ┆        ┆     ┆         ┆ ia     ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1012    ┆ 2018-01 ┆ Female ┆ 44  ┆ Single  ┆ Florid ┆ Basic  ┆ worker ┆ PayPal ┆ 0      ┆ 1778.3 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ a      ┆        ┆ s      ┆        ┆        ┆ 3      │
│         ┆ 41:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1013    ┆ 2018-01 ┆ Male   ┆ 77  ┆ Married ┆ Oregon ┆ Missin ┆ worker ┆ Card   ┆ 0      ┆ 1449.9 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆ g      ┆ s      ┆        ┆        ┆ 8      │
│         ┆ 43:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1014    ┆ 2018-01 ┆ Male   ┆ 54  ┆ Single  ┆ North  ┆ Platin ┆ Employ ┆ Card   ┆ 1      ┆ 2936.9 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ Caroli ┆ um     ┆ ees    ┆        ┆        ┆ 6      │
│         ┆ 43:00.0 ┆        ┆     ┆         ┆ na     ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1015    ┆ 2018-01 ┆ Female ┆ 37  ┆ Married ┆ Arizon ┆ Basic  ┆ Employ ┆ Other  ┆ 1      ┆ null   │
│         ┆ -01T00: ┆        ┆     ┆         ┆ a      ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 44:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1016    ┆ 2018-01 ┆ Female ┆ 75  ┆ Single  ┆ Tennes ┆ Platin ┆ Employ ┆ Card   ┆ 0      ┆ 2870.6 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ see    ┆ um     ┆ ees    ┆        ┆        ┆ 9      │
│         ┆ 52:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1017    ┆ 2018-01 ┆ Female ┆ 77  ┆ Single  ┆ Washin ┆ Platin ┆ Employ ┆ PayPal ┆ 0      ┆ 439.56 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ gton   ┆ um     ┆ ees    ┆        ┆        ┆        │
│         ┆ 53:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1018    ┆ 2018-01 ┆ Male   ┆ 55  ┆ Married ┆ South  ┆ Basic  ┆ Employ ┆ PayPal ┆ 1      ┆ 1274.6 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ Caroli ┆        ┆ ees    ┆        ┆        ┆ 2      │
│         ┆ 57:00.0 ┆        ┆     ┆         ┆ na     ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1019    ┆ 2018-01 ┆ Female ┆ 37  ┆ Married ┆ Missou ┆ Platin ┆ worker ┆ Card   ┆ null   ┆ 1319.6 │
│         ┆ -01T01: ┆        ┆     ┆         ┆ ri     ┆ um     ┆ s      ┆        ┆        ┆ 8      │
│         ┆ 02:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

In [23]:
df.slice(0, 100)  # Retrieve the first 100 rows

shape: (100, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 1000    ┆ 2018-01 ┆ Female ┆ 39  ┆ Single  ┆ Oklaho ┆ Platin ┆ Unempl ┆ Card   ┆ 0      ┆ 1557.5 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ ma     ┆ um     ┆ oyment ┆        ┆        ┆        │
│         ┆ 04:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1001    ┆ 2018-01 ┆ Male   ┆ 34  ┆ Married ┆ Hawaii ┆ Basic  ┆ worker ┆ PayPal ┆ 1      ┆ 153.55 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ s      ┆        ┆        ┆        │
│         ┆ 06:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1002    ┆ 2018-01 ┆ Female ┆ 53  ┆ Married ┆ Iowa   ┆ Basic  ┆ self-e ┆ PayPal ┆ 1      ┆ 2640.9 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ mploye ┆        ┆        ┆ 6      │
│         ┆ 14:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1003    ┆ 2018-01 ┆ Male   ┆ 33  ┆ Married ┆ Wiscon ┆ Basic  ┆ self-e ┆ Card   ┆ 1      ┆ 293.58 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ sin    ┆        ┆ mploye ┆        ┆        ┆        │
│         ┆ 23:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1004    ┆ 2018-01 ┆ Female ┆ 36  ┆ Married ┆ Texas  ┆ Platin ┆ Employ ┆ Card   ┆ 0      ┆ 1608.0 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆ um     ┆ ees    ┆        ┆        ┆ 1      │
│         ┆ 25:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ …       ┆ …       ┆ …      ┆ …   ┆ …       ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 1095    ┆ 2018-01 ┆ Male   ┆ 24  ┆ Single  ┆ Washin ┆ Platin ┆ worker ┆ PayPal ┆ 0      ┆ 2042.6 │
│         ┆ -01T05: ┆        ┆     ┆         ┆ gton   ┆ um     ┆ s      ┆        ┆        ┆ 4      │
│         ┆ 44:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1096    ┆ 2018-01 ┆ Male   ┆ 44  ┆ Married ┆ Indian ┆ Basic  ┆ self-e ┆ PayPal ┆ 1      ┆ null   │
│         ┆ -01T05: ┆        ┆     ┆         ┆ a      ┆        ┆ mploye ┆        ┆        ┆        │
│         ┆ 45:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1097    ┆ 2018-01 ┆ Female ┆ 20  ┆ Married ┆ Nebras ┆ Missin ┆ Employ ┆ PayPal ┆ 1      ┆ 1324.1 │
│         ┆ -01T05: ┆        ┆     ┆         ┆ ka     ┆ g      ┆ ees    ┆        ┆        ┆ 2      │
│         ┆ 47:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1098    ┆ 2018-01 ┆ Female ┆ 28  ┆ Single  ┆ North  ┆ Silver ┆ Employ ┆ Card   ┆ 1      ┆ 1733.6 │
│         ┆ -01T05: ┆        ┆     ┆         ┆ Dakota ┆        ┆ ees    ┆        ┆        ┆ 5      │
│         ┆ 52:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1099    ┆ 2018-01 ┆ Female ┆ 25  ┆ Married ┆ Wyomin ┆ Silver ┆ worker ┆ Other  ┆ 1      ┆ 309.82 │
│         ┆ -01T05: ┆        ┆     ┆         ┆ g      ┆        ┆ s      ┆        ┆        ┆        │
│         ┆ 53:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

In [24]:
df.tail(50)  # Get the last 50 rows

shape: (50, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 1000950 ┆ 2025-01 ┆ Male   ┆ 72  ┆ Married ┆ Minnes ┆ Silver ┆ Employ ┆ PayPal ┆ 0      ┆ 892.56 │
│         ┆ -30T20: ┆        ┆     ┆         ┆ ota    ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 27:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000951 ┆ 2025-01 ┆ Male   ┆ 78  ┆ Married ┆ New    ┆ Basic  ┆ Unempl ┆ Card   ┆ 1      ┆ 95.05  │
│         ┆ -30T20: ┆        ┆     ┆         ┆ Mexico ┆        ┆ oyment ┆        ┆        ┆        │
│         ┆ 30:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000952 ┆ 2025-01 ┆ Male   ┆ 19  ┆ Single  ┆ Vermon ┆ Basic  ┆ self-e ┆ PayPal ┆ 1      ┆ 1967.6 │
│         ┆ -30T20: ┆        ┆     ┆         ┆ t      ┆        ┆ mploye ┆        ┆        ┆        │
│         ┆ 31:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000953 ┆ 2025-01 ┆ Female ┆ 63  ┆ Single  ┆ Louisi ┆ Basic  ┆ Employ ┆ Other  ┆ 1      ┆ 958.83 │
│         ┆ -30T20: ┆        ┆     ┆         ┆ ana    ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 33:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000954 ┆ 2025-01 ┆ Male   ┆ 70  ┆ Single  ┆ New    ┆ Basic  ┆ worker ┆ PayPal ┆ 0      ┆ 2969.2 │
│         ┆ -30T20: ┆        ┆     ┆         ┆ Jersey ┆        ┆ s      ┆        ┆        ┆ 4      │
│         ┆ 34:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ …       ┆ …       ┆ …      ┆ …   ┆ …       ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 1000995 ┆ 2025-01 ┆ Male   ┆ 45  ┆ Single  ┆ Arkans ┆ Gold   ┆ Employ ┆ PayPal ┆ 1      ┆ 1762.7 │
│         ┆ -30T23: ┆        ┆     ┆         ┆ as     ┆        ┆ ees    ┆        ┆        ┆ 6      │
│         ┆ 43:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000996 ┆ 2025-01 ┆ Female ┆ 75  ┆ Married ┆ Virgin ┆ Silver ┆ worker ┆ Other  ┆ 1      ┆ 31.41  │
│         ┆ -30T23: ┆        ┆     ┆         ┆ ia     ┆        ┆ s      ┆        ┆        ┆        │
│         ┆ 45:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000997 ┆ 2025-01 ┆ Female ┆ 61  ┆ Married ┆ Kansas ┆ Basic  ┆ self-e ┆ Other  ┆ 1      ┆ 1699.3 │
│         ┆ -30T23: ┆        ┆     ┆         ┆        ┆        ┆ mploye ┆        ┆        ┆ 1      │
│         ┆ 47:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000998 ┆ 2025-01 ┆ Female ┆ 68  ┆ Married ┆ Utah   ┆ Basic  ┆ Employ ┆ PayPal ┆ 1      ┆ 208.26 │
│         ┆ -30T23: ┆        ┆     ┆         ┆        ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 52:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000999 ┆ 2025-01 ┆ Male   ┆ 55  ┆ Single  ┆ Nevada ┆ Missin ┆ worker ┆ PayPal ┆ 0      ┆ 2063.9 │
│         ┆ -30T23: ┆        ┆     ┆         ┆        ┆ g      ┆ s      ┆        ┆        ┆ 2      │
│         ┆ 57:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

### Sorting and Applying Conditions

**Sorting Data in Ascending Order**

In [25]:
df.sort("Amount_spent", nulls_last=True).head(4)

shape: (4, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 9032    ┆ 2018-01 ┆ Female ┆ 73  ┆ Married ┆ Michig ┆ Gold   ┆ Employ ┆ PayPal ┆ 1      ┆ 2.09   │
│         ┆ -21T18: ┆        ┆     ┆         ┆ an     ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 02:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 12093   ┆ 2018-01 ┆ Female ┆ 73  ┆ Married ┆ Michig ┆ Gold   ┆ Employ ┆ PayPal ┆ 1      ┆ 2.09   │
│         ┆ -29T13: ┆        ┆     ┆         ┆ an     ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 52:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 14260   ┆ 2018-02 ┆ Female ┆ 73  ┆ Married ┆ Michig ┆ Gold   ┆ Employ ┆ PayPal ┆ 1      ┆ 2.09   │
│         ┆ -04T03: ┆        ┆     ┆         ┆ an     ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 34:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 16267   ┆ 2018-02 ┆ Female ┆ 73  ┆ Married ┆ Michig ┆ Gold   ┆ Employ ┆ PayPal ┆ 1      ┆ 2.09   │
│         ┆ -09T09: ┆        ┆     ┆         ┆ an     ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 43:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

**Sorting Data in Descending Order**

In [26]:
df.sort("Amount_spent", descending=True)

shape: (1_000_000, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 1008    ┆ 2018-01 ┆ Male   ┆ 18  ┆ Married ┆ Nevada ┆ Basic  ┆ Employ ┆ Card   ┆ 1      ┆ null   │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 31:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1015    ┆ 2018-01 ┆ Female ┆ 37  ┆ Married ┆ Arizon ┆ Basic  ┆ Employ ┆ Other  ┆ 1      ┆ null   │
│         ┆ -01T00: ┆        ┆     ┆         ┆ a      ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 44:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1025    ┆ 2018-01 ┆ Male   ┆ 21  ┆ Married ┆ Florid ┆ Silver ┆ Unempl ┆ Card   ┆ 0      ┆ null   │
│         ┆ -01T01: ┆        ┆     ┆         ┆ a      ┆        ┆ oyment ┆        ┆        ┆        │
│         ┆ 13:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1039    ┆ 2018-01 ┆ Female ┆ 37  ┆ Single  ┆ Washin ┆ Basic  ┆ self-e ┆ PayPal ┆ 1      ┆ null   │
│         ┆ -01T01: ┆        ┆     ┆         ┆ gton   ┆        ┆ mploye ┆        ┆        ┆        │
│         ┆ 51:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1063    ┆ 2018-01 ┆ Male   ┆ 39  ┆ Married ┆ Montan ┆ Platin ┆ Unempl ┆ Other  ┆ 0      ┆ null   │
│         ┆ -01T03: ┆        ┆     ┆         ┆ a      ┆ um     ┆ oyment ┆        ┆        ┆        │
│         ┆ 41:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ …       ┆ …       ┆ …      ┆ …   ┆ …       ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 989972  ┆ 2025-01 ┆ Female ┆ 73  ┆ Married ┆ Michig ┆ Gold   ┆ Employ ┆ PayPal ┆ 1      ┆ 2.09   │
│         ┆ -02T13: ┆        ┆     ┆         ┆ an     ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 57:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 989980  ┆ 2025-01 ┆ Female ┆ 73  ┆ Married ┆ Michig ┆ Gold   ┆ Employ ┆ PayPal ┆ 1      ┆ 2.09   │
│         ┆ -02T14: ┆        ┆     ┆         ┆ an     ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 28:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 993301  ┆ 2025-01 ┆ Female ┆ 73  ┆ Married ┆ Michig ┆ Gold   ┆ Employ ┆ PayPal ┆ 1      ┆ 2.09   │
│         ┆ -11T12: ┆        ┆     ┆         ┆ an     ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 05:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 996137  ┆ 2025-01 ┆ Female ┆ 73  ┆ Married ┆ Michig ┆ Gold   ┆ Employ ┆ PayPal ┆ 1      ┆ 2.09   │
│         ┆ -18T11: ┆        ┆     ┆         ┆ an     ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 52:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000180 ┆ 2025-01 ┆ Female ┆ 73  ┆ Married ┆ Michig ┆ Gold   ┆ Employ ┆ PayPal ┆ 1      ┆ 2.09   │
│         ┆ -28T22: ┆        ┆     ┆         ┆ an     ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 45:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

**Sorting by Multiple Columns**

In [27]:
df.sort(["Gender", "Amount_spent"], descending=[False, True], nulls_last=True).head(4)

shape: (4, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 1270    ┆ 2018-01 ┆ Female ┆ 77  ┆ Married ┆ New    ┆ Platin ┆ worker ┆ Card   ┆ 0      ┆ 2999.9 │
│         ┆ -01T16: ┆        ┆     ┆         ┆ Mexico ┆ um     ┆ s      ┆        ┆        ┆ 8      │
│         ┆ 21:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 3182    ┆ 2018-01 ┆ Female ┆ 77  ┆ Married ┆ New    ┆ Platin ┆ worker ┆ Card   ┆ 0      ┆ 2999.9 │
│         ┆ -06T20: ┆        ┆     ┆         ┆ Mexico ┆ um     ┆ s      ┆        ┆        ┆ 8      │
│         ┆ 42:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 7065    ┆ 2018-01 ┆ Female ┆ 77  ┆ Married ┆ New    ┆ Platin ┆ worker ┆ Card   ┆ 0      ┆ 2999.9 │
│         ┆ -16T18: ┆        ┆     ┆         ┆ Mexico ┆ um     ┆ s      ┆        ┆        ┆ 8      │
│         ┆ 30:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 8747    ┆ 2018-01 ┆ Female ┆ 77  ┆ Married ┆ New    ┆ Platin ┆ worker ┆ Card   ┆ 0      ┆ 2999.9 │
│         ┆ -21T00: ┆        ┆     ┆         ┆ Mexico ┆ um     ┆ s      ┆        ┆        ┆ 8      │
│         ┆ 15:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

### Applying Complex Conditional Queries

**Find Female Customers Who Spent More Than $100**

In [28]:
df.filter((pl.col("Amount_spent") > 100) & (pl.col("Gender") == "Female"))

shape: (466_044, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 1000    ┆ 2018-01 ┆ Female ┆ 39  ┆ Single  ┆ Oklaho ┆ Platin ┆ Unempl ┆ Card   ┆ 0      ┆ 1557.5 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ ma     ┆ um     ┆ oyment ┆        ┆        ┆        │
│         ┆ 04:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1002    ┆ 2018-01 ┆ Female ┆ 53  ┆ Married ┆ Iowa   ┆ Basic  ┆ self-e ┆ PayPal ┆ 1      ┆ 2640.9 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ mploye ┆        ┆        ┆ 6      │
│         ┆ 14:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1004    ┆ 2018-01 ┆ Female ┆ 36  ┆ Married ┆ Texas  ┆ Platin ┆ Employ ┆ Card   ┆ 0      ┆ 1608.0 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆ um     ┆ ees    ┆        ┆        ┆ 1      │
│         ┆ 25:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1006    ┆ 2018-01 ┆ Female ┆ 55  ┆ Single  ┆ Ohio   ┆ Silver ┆ Unempl ┆ PayPal ┆ 0      ┆ 1553.6 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ oyment ┆        ┆        ┆ 1      │
│         ┆ 29:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1007    ┆ 2018-01 ┆ Female ┆ 35  ┆ Married ┆ Hawaii ┆ Basic  ┆ worker ┆ Other  ┆ 1      ┆ 1851.5 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ s      ┆        ┆        ┆ 8      │
│         ┆ 29:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ …       ┆ …       ┆ …      ┆ …   ┆ …       ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 1000992 ┆ 2025-01 ┆ Female ┆ 25  ┆ Married ┆ Nebras ┆ Basic  ┆ worker ┆ PayPal ┆ 0      ┆ 1735.0 │
│         ┆ -30T23: ┆        ┆     ┆         ┆ ka     ┆        ┆ s      ┆        ┆        ┆ 7      │
│         ┆ 23:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000993 ┆ 2025-01 ┆ Female ┆ 18  ┆ Married ┆ Alabam ┆ Silver ┆ worker ┆ PayPal ┆ null   ┆ 2091.7 │
│         ┆ -30T23: ┆        ┆     ┆         ┆ a      ┆        ┆ s      ┆        ┆        ┆ 3      │
│         ┆ 29:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000994 ┆ 2025-01 ┆ Female ┆ 51  ┆ Single  ┆ West   ┆ Platin ┆ Unempl ┆ Card   ┆ 0      ┆ 522.04 │
│         ┆ -30T23: ┆        ┆     ┆         ┆ Virgin ┆ um     ┆ oyment ┆        ┆        ┆        │
│         ┆ 29:00.0 ┆        ┆     ┆         ┆ ia     ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000997 ┆ 2025-01 ┆ Female ┆ 61  ┆ Married ┆ Kansas ┆ Basic  ┆ self-e ┆ Other  ┆ 1      ┆ 1699.3 │
│         ┆ -30T23: ┆        ┆     ┆         ┆        ┆        ┆ mploye ┆        ┆        ┆ 1      │
│         ┆ 47:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000998 ┆ 2025-01 ┆ Female ┆ 68  ┆ Married ┆ Utah   ┆ Basic  ┆ Employ ┆ PayPal ┆ 1      ┆ 208.26 │
│         ┆ -30T23: ┆        ┆     ┆         ┆        ┆        ┆ ees    ┆        ┆        ┆        │
│         ┆ 52:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

**Get Customers Aged Between 25 and 40**

In [29]:
df.filter((pl.col("Age") >= 25) & (pl.col("Age") <= 40))

shape: (247_320, 11)
┌─────────┬─────────┬────────┬─────┬─────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transac ┆ Gender ┆ Age ┆ Marital ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ tion_da ┆ ---    ┆ --- ┆ _status ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ te      ┆ str    ┆ i64 ┆ ---     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ i64     ┆ ---     ┆        ┆     ┆ str     ┆ str    ┆ str    ┆ ---    ┆ ---    ┆ i64    ┆ f64    │
│         ┆ str     ┆        ┆     ┆         ┆        ┆        ┆ str    ┆ str    ┆        ┆        │
╞═════════╪═════════╪════════╪═════╪═════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 1000    ┆ 2018-01 ┆ Female ┆ 39  ┆ Single  ┆ Oklaho ┆ Platin ┆ Unempl ┆ Card   ┆ 0      ┆ 1557.5 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ ma     ┆ um     ┆ oyment ┆        ┆        ┆        │
│         ┆ 04:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1001    ┆ 2018-01 ┆ Male   ┆ 34  ┆ Married ┆ Hawaii ┆ Basic  ┆ worker ┆ PayPal ┆ 1      ┆ 153.55 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ s      ┆        ┆        ┆        │
│         ┆ 06:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1003    ┆ 2018-01 ┆ Male   ┆ 33  ┆ Married ┆ Wiscon ┆ Basic  ┆ self-e ┆ Card   ┆ 1      ┆ 293.58 │
│         ┆ -01T00: ┆        ┆     ┆         ┆ sin    ┆        ┆ mploye ┆        ┆        ┆        │
│         ┆ 23:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1004    ┆ 2018-01 ┆ Female ┆ 36  ┆ Married ┆ Texas  ┆ Platin ┆ Employ ┆ Card   ┆ 0      ┆ 1608.0 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆ um     ┆ ees    ┆        ┆        ┆ 1      │
│         ┆ 25:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1007    ┆ 2018-01 ┆ Female ┆ 35  ┆ Married ┆ Hawaii ┆ Basic  ┆ worker ┆ Other  ┆ 1      ┆ 1851.5 │
│         ┆ -01T00: ┆        ┆     ┆         ┆        ┆        ┆ s      ┆        ┆        ┆ 8      │
│         ┆ 29:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ …       ┆ …       ┆ …      ┆ …   ┆ …       ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      ┆ …      │
│ 1000978 ┆ 2025-01 ┆ Female ┆ 31  ┆ Single  ┆ New    ┆ Silver ┆ self-e ┆ PayPal ┆ 1      ┆ null   │
│         ┆ -30T22: ┆        ┆     ┆         ┆ York   ┆        ┆ mploye ┆        ┆        ┆        │
│         ┆ 33:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000979 ┆ 2025-01 ┆ Female ┆ 40  ┆ Single  ┆ Alaska ┆ Platin ┆ worker ┆ Other  ┆ 1      ┆ null   │
│         ┆ -30T22: ┆        ┆     ┆         ┆        ┆ um     ┆ s      ┆        ┆        ┆        │
│         ┆ 36:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000985 ┆ 2025-01 ┆ Female ┆ 37  ┆ Married ┆ Nevada ┆ Silver ┆ self-e ┆ Other  ┆ 0      ┆ 507.25 │
│         ┆ -30T23: ┆        ┆     ┆         ┆        ┆        ┆ mploye ┆        ┆        ┆        │
│         ┆ 11:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000988 ┆ 2025-01 ┆ Female ┆ 39  ┆ Single  ┆ Florid ┆ Basic  ┆ self-e ┆ Card   ┆ 1      ┆ 1305.5 │
│         ┆ -30T23: ┆        ┆     ┆         ┆ a      ┆        ┆ mploye ┆        ┆        ┆ 2      │
│         ┆ 19:00.0 ┆        ┆     ┆         ┆        ┆        ┆ d      ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│ 1000992 ┆ 2025-01 ┆ Female ┆ 25  ┆ Married ┆ Nebras ┆ Basic  ┆ worker ┆ PayPal ┆ 0      ┆ 1735.0 │
│         ┆ -30T23: ┆        ┆     ┆         ┆ ka     ┆        ┆ s      ┆        ┆        ┆ 7      │
│         ┆ 23:00.0 ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
│         ┆ 00000   ┆        ┆     ┆         ┆        ┆        ┆        ┆        ┆        ┆        │
└─────────┴─────────┴────────┴─────┴─────────┴────────┴────────┴────────┴────────┴────────┴────────┘

## 4. Data Cleaning and Preprocessing

### Handling Missing Values

**Checking for Missing Values**

In [30]:
df_clean = df
df_clean.null_count()

shape: (1, 11)
┌─────────┬────────┬────────┬───────┬────────┬────────┬────────┬────────┬────────┬────────┬────────┐
│ Transac ┆ Transa ┆ Gender ┆ Age   ┆ Marita ┆ State_ ┆ Segmen ┆ Employ ┆ Paymen ┆ Referr ┆ Amount │
│ tion_ID ┆ ction_ ┆ ---    ┆ ---   ┆ l_stat ┆ names  ┆ t      ┆ ees_st ┆ t_meth ┆ al     ┆ _spent │
│ ---     ┆ date   ┆ u32    ┆ u32   ┆ us     ┆ ---    ┆ ---    ┆ atus   ┆ od     ┆ ---    ┆ ---    │
│ u32     ┆ ---    ┆        ┆       ┆ ---    ┆ u32    ┆ u32    ┆ ---    ┆ ---    ┆ u32    ┆ u32    │
│         ┆ u32    ┆        ┆       ┆ u32    ┆        ┆        ┆ u32    ┆ u32    ┆        ┆        │
╞═════════╪════════╪════════╪═══════╪════════╪════════╪════════╪════════╪════════╪════════╪════════╡
│ 0       ┆ 0      ┆ 11052  ┆ 16654 ┆ 0      ┆ 0      ┆ 0      ┆ 10225  ┆ 0      ┆ 61812  ┆ 96065  │
└─────────┴────────┴────────┴───────┴────────┴────────┴────────┴────────┴────────┴────────┴────────┘

**Dropping Missing Values**

In [31]:
df_clean = df.drop("Referral")  # Removes the 'Referral' column
df_clean.head(4)

shape: (4, 10)
┌──────────┬──────────┬────────┬─────┬──────────┬──────────┬─────────┬─────────┬─────────┬─────────┐
│ Transact ┆ Transact ┆ Gender ┆ Age ┆ Marital_ ┆ State_na ┆ Segment ┆ Employe ┆ Payment ┆ Amount_ │
│ ion_ID   ┆ ion_date ┆ ---    ┆ --- ┆ status   ┆ mes      ┆ ---     ┆ es_stat ┆ _method ┆ spent   │
│ ---      ┆ ---      ┆ str    ┆ i64 ┆ ---      ┆ ---      ┆ str     ┆ us      ┆ ---     ┆ ---     │
│ i64      ┆ str      ┆        ┆     ┆ str      ┆ str      ┆         ┆ ---     ┆ str     ┆ f64     │
│          ┆          ┆        ┆     ┆          ┆          ┆         ┆ str     ┆         ┆         │
╞══════════╪══════════╪════════╪═════╪══════════╪══════════╪═════════╪═════════╪═════════╪═════════╡
│ 1000     ┆ 2018-01- ┆ Female ┆ 39  ┆ Single   ┆ Oklahoma ┆ Platinu ┆ Unemplo ┆ Card    ┆ 1557.5  │
│          ┆ 01T00:04 ┆        ┆     ┆          ┆          ┆ m       ┆ yment   ┆         ┆         │
│          ┆ :00.0000 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ 00       ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│ 1001     ┆ 2018-01- ┆ Male   ┆ 34  ┆ Married  ┆ Hawaii   ┆ Basic   ┆ workers ┆ PayPal  ┆ 153.55  │
│          ┆ 01T00:06 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ :00.0000 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ 00       ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│ 1002     ┆ 2018-01- ┆ Female ┆ 53  ┆ Married  ┆ Iowa     ┆ Basic   ┆ self-em ┆ PayPal  ┆ 2640.96 │
│          ┆ 01T00:14 ┆        ┆     ┆          ┆          ┆         ┆ ployed  ┆         ┆         │
│          ┆ :00.0000 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ 00       ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│ 1003     ┆ 2018-01- ┆ Male   ┆ 33  ┆ Married  ┆ Wisconsi ┆ Basic   ┆ self-em ┆ Card    ┆ 293.58  │
│          ┆ 01T00:23 ┆        ┆     ┆          ┆ n        ┆         ┆ ployed  ┆         ┆         │
│          ┆ :00.0000 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ 00       ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
└──────────┴──────────┴────────┴─────┴──────────┴──────────┴─────────┴─────────┴─────────┴─────────┘

In [32]:
df_clean.drop_nulls(subset=["Gender"])

shape: (988_948, 10)
┌──────────┬──────────┬────────┬─────┬──────────┬──────────┬─────────┬─────────┬─────────┬─────────┐
│ Transact ┆ Transact ┆ Gender ┆ Age ┆ Marital_ ┆ State_na ┆ Segment ┆ Employe ┆ Payment ┆ Amount_ │
│ ion_ID   ┆ ion_date ┆ ---    ┆ --- ┆ status   ┆ mes      ┆ ---     ┆ es_stat ┆ _method ┆ spent   │
│ ---      ┆ ---      ┆ str    ┆ i64 ┆ ---      ┆ ---      ┆ str     ┆ us      ┆ ---     ┆ ---     │
│ i64      ┆ str      ┆        ┆     ┆ str      ┆ str      ┆         ┆ ---     ┆ str     ┆ f64     │
│          ┆          ┆        ┆     ┆          ┆          ┆         ┆ str     ┆         ┆         │
╞══════════╪══════════╪════════╪═════╪══════════╪══════════╪═════════╪═════════╪═════════╪═════════╡
│ 1000     ┆ 2018-01- ┆ Female ┆ 39  ┆ Single   ┆ Oklahoma ┆ Platinu ┆ Unemplo ┆ Card    ┆ 1557.5  │
│          ┆ 01T00:04 ┆        ┆     ┆          ┆          ┆ m       ┆ yment   ┆         ┆         │
│          ┆ :00.0000 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ 00       ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│ 1001     ┆ 2018-01- ┆ Male   ┆ 34  ┆ Married  ┆ Hawaii   ┆ Basic   ┆ workers ┆ PayPal  ┆ 153.55  │
│          ┆ 01T00:06 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ :00.0000 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ 00       ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│ 1002     ┆ 2018-01- ┆ Female ┆ 53  ┆ Married  ┆ Iowa     ┆ Basic   ┆ self-em ┆ PayPal  ┆ 2640.96 │
│          ┆ 01T00:14 ┆        ┆     ┆          ┆          ┆         ┆ ployed  ┆         ┆         │
│          ┆ :00.0000 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ 00       ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│ 1003     ┆ 2018-01- ┆ Male   ┆ 33  ┆ Married  ┆ Wisconsi ┆ Basic   ┆ self-em ┆ Card    ┆ 293.58  │
│          ┆ 01T00:23 ┆        ┆     ┆          ┆ n        ┆         ┆ ployed  ┆         ┆         │
│          ┆ :00.0000 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ 00       ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│ 1004     ┆ 2018-01- ┆ Female ┆ 36  ┆ Married  ┆ Texas    ┆ Platinu ┆ Employe ┆ Card    ┆ 1608.01 │
│          ┆ 01T00:25 ┆        ┆     ┆          ┆          ┆ m       ┆ es      ┆         ┆         │
│          ┆ :00.0000 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ 00       ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│ …        ┆ …        ┆ …      ┆ …   ┆ …        ┆ …        ┆ …       ┆ …       ┆ …       ┆ …       │
│ 1000995  ┆ 2025-01- ┆ Male   ┆ 45  ┆ Single   ┆ Arkansas ┆ Gold    ┆ Employe ┆ PayPal  ┆ 1762.76 │
│          ┆ 30T23:43 ┆        ┆     ┆          ┆          ┆         ┆ es      ┆         ┆         │
│          ┆ :00.0000 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ 00       ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│ 1000996  ┆ 2025-01- ┆ Female ┆ 75  ┆ Married  ┆ Virginia ┆ Silver  ┆ workers ┆ Other   ┆ 31.41   │
│          ┆ 30T23:45 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ :00.0000 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ 00       ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│ 1000997  ┆ 2025-01- ┆ Female ┆ 61  ┆ Married  ┆ Kansas   ┆ Basic   ┆ self-em ┆ Other   ┆ 1699.31 │
│          ┆ 30T23:47 ┆        ┆     ┆          ┆          ┆         ┆ ployed  ┆         ┆         │
│          ┆ :00.0000 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ 00       ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│ 1000998  ┆ 2025-01- ┆ Female ┆ 68  ┆ Married  ┆ Utah     ┆ Basic   ┆ Employe ┆ PayPal  ┆ 208.26  │
│          ┆ 30T23:52 ┆        ┆     ┆          ┆          ┆         ┆ es      ┆         ┆         │
│          ┆ :00.0000 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ 00       ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│ 1000999  ┆ 2025-01- ┆ Male   ┆ 55  ┆ Single   ┆ Nevada   ┆ Missing ┆ workers ┆ PayPal  ┆ 2063.92 │
│          ┆ 30T23:57 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ :00.0000 ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
│          ┆ 00       ┆        ┆     ┆          ┆          ┆         ┆         ┆         ┆         │
└──────────┴──────────┴────────┴─────┴──────────┴──────────┴─────────┴─────────┴─────────┴─────────┘

**Filling Missing Values (Imputation)**

In [33]:
# replace missing values in Gender with "Unknown":
df_clean = df_clean.with_columns(pl.col("Gender").fill_null("Unknown"))

In [34]:
# replace missing values with zero or another fixed value:
df_clean = df_clean.with_columns(pl.col("Amount_spent").fill_null(0))

#### Filling with Statistical Measures

**Replace missing values in Age with the median:**

In [35]:
median_age = df_clean["Age"].median()
df_clean = df_clean.with_columns(pl.col("Age").fill_null(median_age))

**Replace missing values in Amount_spent with the mean:**

In [36]:
df_clean = df
mean_spent = df_clean["Amount_spent"].mean()
df_clean = df_clean.with_columns(pl.col("Amount_spent").fill_null(mean_spent))

**Replace missing values in Gender with the most frequent value (mode):**

In [37]:
mode_gender = df["Gender"].mode()[0]  # Get most common value
df = df.with_columns(pl.col("Gender").fill_null(mode_gender))

**Forward Filling** use the previous row’s value to fill the missing value

In [38]:
df_clean = df
df_clean = df_clean.with_columns(pl.col("Amount_spent").fill_null(strategy="forward"))

**Backward fill** (use the next row’s value to fill the missing value):

In [39]:
df_clean = df
df = df.with_columns(pl.col("Amount_spent").fill_null(strategy="backward"))

### Data Type Conversion

**Checking Data Types**

In [40]:
df.schema

Schema([('Transaction_ID', Int64),
        ('Transaction_date', String),
        ('Gender', String),
        ('Age', Int64),
        ('Marital_status', String),
        ('State_names', String),
        ('Segment', String),
        ('Employees_status', String),
        ('Payment_method', String),
        ('Referral', Int64),
        ('Amount_spent', Float64)])

**Convert Referral from Int64 to String**

In [41]:
df = df.with_columns(pl.col("Referral").cast(pl.Utf8))  # Convert to String for better readability

In [42]:
df.schema

Schema([('Transaction_ID', Int64),
        ('Transaction_date', String),
        ('Gender', String),
        ('Age', Int64),
        ('Marital_status', String),
        ('State_names', String),
        ('Segment', String),
        ('Employees_status', String),
        ('Payment_method', String),
        ('Referral', String),
        ('Amount_spent', Float64)])

**Convert Age from Int64 to Float64**

In [43]:
df = df.with_columns(pl.col("Age").cast(pl.Float64))

**Convert `Transaction_date` from text to a real timestamp**

The CSV stores each transaction time as text, such as `2018-01-01T00:04:00.000000`. Parse it so date functions work, then format it any way you like.

In [44]:
df = df.with_columns(pl.col("Transaction_date").str.to_datetime())

# Once it is a datetime, format it for a report:
df = df.with_columns(pl.col("Transaction_date").dt.strftime("%d %b %Y").alias("Pretty_date"))  # 01 Jan 2018

In [45]:
df.head()

shape: (5, 12)
┌────────┬────────┬────────┬──────┬────────┬───────┬───────┬───────┬───────┬───────┬───────┬───────┐
│ Transa ┆ Transa ┆ Gender ┆ Age  ┆ Marita ┆ State ┆ Segme ┆ Emplo ┆ Payme ┆ Refer ┆ Amoun ┆ Prett │
│ ction_ ┆ ction_ ┆ ---    ┆ ---  ┆ l_stat ┆ _name ┆ nt    ┆ yees_ ┆ nt_me ┆ ral   ┆ t_spe ┆ y_dat │
│ ID     ┆ date   ┆ str    ┆ f64  ┆ us     ┆ s     ┆ ---   ┆ statu ┆ thod  ┆ ---   ┆ nt    ┆ e     │
│ ---    ┆ ---    ┆        ┆      ┆ ---    ┆ ---   ┆ str   ┆ s     ┆ ---   ┆ str   ┆ ---   ┆ ---   │
│ i64    ┆ dateti ┆        ┆      ┆ str    ┆ str   ┆       ┆ ---   ┆ str   ┆       ┆ f64   ┆ str   │
│        ┆ me[μs] ┆        ┆      ┆        ┆       ┆       ┆ str   ┆       ┆       ┆       ┆       │
╞════════╪════════╪════════╪══════╪════════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╪═══════╡
│ 1000   ┆ 2018-0 ┆ Female ┆ 39.0 ┆ Single ┆ Oklah ┆ Plati ┆ Unemp ┆ Card  ┆ 0     ┆ 1557. ┆ 01    │
│        ┆ 1-01   ┆        ┆      ┆        ┆ oma   ┆ num   ┆ loyme ┆       ┆       ┆ 5     ┆ Jan   │
│        ┆ 00:04: ┆        ┆      ┆        ┆       ┆       ┆ nt    ┆       ┆       ┆       ┆ 2018  │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 1001   ┆ 2018-0 ┆ Male   ┆ 34.0 ┆ Marrie ┆ Hawai ┆ Basic ┆ worke ┆ PayPa ┆ 1     ┆ 153.5 ┆ 01    │
│        ┆ 1-01   ┆        ┆      ┆ d      ┆ i     ┆       ┆ rs    ┆ l     ┆       ┆ 5     ┆ Jan   │
│        ┆ 00:06: ┆        ┆      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ 2018  │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 1002   ┆ 2018-0 ┆ Female ┆ 53.0 ┆ Marrie ┆ Iowa  ┆ Basic ┆ self- ┆ PayPa ┆ 1     ┆ 2640. ┆ 01    │
│        ┆ 1-01   ┆        ┆      ┆ d      ┆       ┆       ┆ emplo ┆ l     ┆       ┆ 96    ┆ Jan   │
│        ┆ 00:14: ┆        ┆      ┆        ┆       ┆       ┆ yed   ┆       ┆       ┆       ┆ 2018  │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 1003   ┆ 2018-0 ┆ Male   ┆ 33.0 ┆ Marrie ┆ Wisco ┆ Basic ┆ self- ┆ Card  ┆ 1     ┆ 293.5 ┆ 01    │
│        ┆ 1-01   ┆        ┆      ┆ d      ┆ nsin  ┆       ┆ emplo ┆       ┆       ┆ 8     ┆ Jan   │
│        ┆ 00:23: ┆        ┆      ┆        ┆       ┆       ┆ yed   ┆       ┆       ┆       ┆ 2018  │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
│ 1004   ┆ 2018-0 ┆ Female ┆ 36.0 ┆ Marrie ┆ Texas ┆ Plati ┆ Emplo ┆ Card  ┆ 0     ┆ 1608. ┆ 01    │
│        ┆ 1-01   ┆        ┆      ┆ d      ┆       ┆ num   ┆ yees  ┆       ┆       ┆ 01    ┆ Jan   │
│        ┆ 00:25: ┆        ┆      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆ 2018  │
│        ┆ 00     ┆        ┆      ┆        ┆       ┆       ┆       ┆       ┆       ┆       ┆       │
└────────┴────────┴────────┴──────┴────────┴───────┴───────┴───────┴───────┴───────┴───────┴───────┘

## 5. Advanced Data Transformations

#### GroupBy and Aggregations

**To calculate total spending per gender:**

In [46]:
df.group_by("Gender").agg(pl.sum("Amount_spent"))

shape: (2, 2)
┌────────┬──────────────┐
│ Gender ┆ Amount_spent │
│ ---    ┆ ---          │
│ str    ┆ f64          │
╞════════╪══════════════╡
│ Female ┆ 7.8495e8     │
│ Male   ┆ 6.3171e8     │
└────────┴──────────────┘

**To calculate total amount spent by Gender and Payment Method:**

In [47]:
df.group_by(["Gender", "Payment_method"]) \
  .agg(pl.sum("Amount_spent").cast(pl.Int64)) \
  .sort(["Gender", "Payment_method"])

shape: (6, 3)
┌────────┬────────────────┬──────────────┐
│ Gender ┆ Payment_method ┆ Amount_spent │
│ ---    ┆ ---            ┆ ---          │
│ str    ┆ str            ┆ i64          │
╞════════╪════════════════╪══════════════╡
│ Female ┆ Card           ┆ 251092780    │
│ Female ┆ Other          ┆ 186728178    │
│ Female ┆ PayPal         ┆ 347128441    │
│ Male   ┆ Card           ┆ 166060495    │
│ Male   ┆ Other          ┆ 156921359    │
│ Male   ┆ PayPal         ┆ 308726924    │
└────────┴────────────────┴──────────────┘

**To calculate multiple statistics:**

In [48]:
df.group_by("Gender").agg([
    pl.sum("Amount_spent").alias("Total Spent"),
    pl.mean("Age").alias("Average Age"),
    pl.len().alias("Customer Count")
])

shape: (2, 4)
┌────────┬─────────────┬─────────────┬────────────────┐
│ Gender ┆ Total Spent ┆ Average Age ┆ Customer Count │
│ ---    ┆ ---         ┆ ---         ┆ ---            │
│ str    ┆ f64         ┆ f64         ┆ u32            │
╞════════╪═════════════╪═════════════╪════════════════╡
│ Male   ┆ 6.3171e8    ┆ 46.494462   ┆ 449117         │
│ Female ┆ 7.8495e8    ┆ 46.773035   ┆ 550883         │
└────────┴─────────────┴─────────────┴────────────────┘

### Pivoting DataFrames

In [49]:
df.pivot(
    values="Amount_spent",
    index="Gender",
    on="Payment_method",
    aggregate_function="sum"
)

shape: (2, 4)
┌────────┬──────────┬──────────┬──────────┐
│ Gender ┆ Card     ┆ PayPal   ┆ Other    │
│ ---    ┆ ---      ┆ ---      ┆ ---      │
│ str    ┆ f64      ┆ f64      ┆ f64      │
╞════════╪══════════╪══════════╪══════════╡
│ Female ┆ 2.5109e8 ┆ 3.4713e8 ┆ 1.8673e8 │
│ Male   ┆ 1.6606e8 ┆ 3.0873e8 ┆ 1.5692e8 │
└────────┴──────────┴──────────┴──────────┘

### Rolling Averages for Time Series

Total the spending per day, then average each day with the six before it (a 7-day rolling average). This uses the datetime column created in the data type section.

In [50]:
daily = (
    df.group_by(pl.col("Transaction_date").dt.date().alias("Day"))  # timestamp -> calendar day
    .agg(pl.sum("Amount_spent").alias("Daily_spent"))
    .sort("Day")
    .with_columns(pl.col("Daily_spent").rolling_mean(window_size=7).alias("7_day_avg"))
)
daily.tail(3)

shape: (3, 3)
┌────────────┬─────────────┬───────────────┐
│ Day        ┆ Daily_spent ┆ 7_day_avg     │
│ ---        ┆ ---         ┆ ---           │
│ date       ┆ f64         ┆ f64           │
╞════════════╪═════════════╪═══════════════╡
│ 2025-01-28 ┆ 530817.52   ┆ 549678.815714 │
│ 2025-01-29 ┆ 540848.25   ┆ 546990.124286 │
│ 2025-01-30 ┆ 551348.83   ┆ 547740.904286 │
└────────────┴─────────────┴───────────────┘

## 6. Performance Optimization Techniques

### Using LazyFrames for Efficient Execution

In [51]:
df_lazy = pl.scan_csv(DATA_PATH)

In [52]:
df_final = df_lazy.filter(pl.col("Amount_spent") > 100).collect()

**See what the optimizer does with `.explain()`**

The plan shows Polars reads only 2 of the 11 columns (`PROJECT 2/11 COLUMNS`) and filters while reading the file.

In [53]:
query = (
    pl.scan_csv(DATA_PATH)
    .filter(pl.col("Amount_spent") > 100)
    .group_by("Gender")
    .agg(pl.sum("Amount_spent"))
)
print(query.explain())

# For files bigger than your RAM, process in chunks with the streaming engine:
query.collect(engine="streaming")

shape: (3, 2)
┌────────┬──────────────┐
│ Gender ┆ Amount_spent │
│ ---    ┆ ---          │
│ str    ┆ f64          │
╞════════╪══════════════╡
│ null   ┆ 1.3865e7     │
│ Female ┆ 6.9032e8     │
│ Male   ┆ 5.7407e8     │
└────────┴──────────────┘

### Memory Management (Efficient Data Types)

**Converting Data Types for Optimization**

In [54]:
df = pl.read_csv(
    DATA_PATH,
    schema_overrides={"Transaction_ID": pl.Int32, "Amount_spent": pl.Float32}
)

**To check how much memory a DataFrame consumes:**

In [55]:
df.estimated_size(unit = 'mb')

86.55259037017822

### Multi-threaded Processing

**Parallel Processing in Aggregations**

In [56]:
df.group_by("Gender").agg(pl.sum("Amount_spent"))

shape: (3, 2)
┌────────┬──────────────┐
│ Gender ┆ Amount_spent │
│ ---    ┆ ---          │
│ str    ┆ f32          │
╞════════╪══════════════╡
│ null   ┆ 1.3883243e7  │
│ Female ┆ 6.91295296e8 │
│ Male   ┆ 5.74907328e8 │
└────────┴──────────────┘

In [57]:
# How many threads Polars uses (by default one per CPU core)
pl.thread_pool_size()

# To limit it, set this environment variable BEFORE importing polars (e.g. at the top of a script):
# import os; os.environ["POLARS_MAX_THREADS"] = "4"

16

## 7. SQL-like Queries with Polars

**Running SQL Queries in Polars**

In [58]:
# Quickest way: df.sql(), where the table is always called "self"
df.sql("SELECT Gender, SUM(Amount_spent) AS Total_spent FROM self GROUP BY Gender")

shape: (3, 2)
┌────────┬──────────────┐
│ Gender ┆ Total_spent  │
│ ---    ┆ ---          │
│ str    ┆ f32          │
╞════════╪══════════════╡
│ null   ┆ 1.3883243e7  │
│ Female ┆ 6.91295296e8 │
│ Male   ┆ 5.74907328e8 │
└────────┴──────────────┘

In [59]:
# For queries across several tables, register them in a SQLContext
from polars import SQLContext

sql_context = SQLContext()

# Register DataFrame as a SQL table
sql_context.register("customers", df)

# Run SQL query (execute() returns a LazyFrame; collect() runs it)
result = sql_context.execute("SELECT Gender, SUM(Amount_spent) FROM customers GROUP BY Gender")
df_result = result.collect()
print(df_result)

shape: (3, 2)
┌────────┬──────────────┐
│ Gender ┆ Amount_spent │
│ ---    ┆ ---          │
│ str    ┆ f32          │
╞════════╪══════════════╡
│ null   ┆ 1.3883243e7  │
│ Female ┆ 6.91295296e8 │
│ Male   ┆ 5.74907328e8 │
└────────┴──────────────┘

**Filtering and Aggregation with SQL Queries**

In [60]:
result = sql_context.execute("""
    SELECT Gender, Payment_method, COUNT(*) AS Total_Transactions, AVG(Amount_spent) AS Avg_Spent
    FROM customers
    WHERE Amount_spent > 50
    GROUP BY Gender, Payment_method
    ORDER BY Avg_Spent DESC
""").collect()

In [61]:
print(result)

shape: (9, 4)
┌────────┬────────────────┬────────────────────┬─────────────┐
│ Gender ┆ Payment_method ┆ Total_Transactions ┆ Avg_Spent   │
│ ---    ┆ ---            ┆ ---                ┆ ---         │
│ str    ┆ str            ┆ i64                ┆ f32         │
╞════════╪════════════════╪════════════════════╪═════════════╡
│ Female ┆ Other          ┆ 113033             ┆ 1488.96936  │
│ Male   ┆ PayPal         ┆ 195568             ┆ 1462.975586 │
│ Female ┆ Card           ┆ 152513             ┆ 1449.810059 │
│ Male   ┆ Other          ┆ 99771              ┆ 1443.268555 │
│ Female ┆ PayPal         ┆ 211382             ┆ 1427.339722 │
│ null   ┆ Card           ┆ 4051               ┆ 1398.654053 │
│ null   ┆ PayPal         ┆ 4354               ┆ 1353.336182 │
│ Male   ┆ Card           ┆ 107065             ┆ 1350.705933 │
│ null   ┆ Other          ┆ 1852               ┆ 1255.329956 │
└────────┴────────────────┴────────────────────┴─────────────┘